version: 2

project_name: gen-dto

before:
  hooks:
    - go mod tidy

builds:
  - id: gen-dto
    main: ./cmd/gen-dto
    binary: gen-dto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: binaries
    ids:
      - gen-dto
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: seitarof
    name: gen-dto

brews:
  - name: gen-dto
    ids:
      - binaries
    repository:
      owner: seitarof
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/seitarof/gen-dto
    description: Generate bidirectional DTO conversion code for Go structs.
    license: MIT
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
    test: |
      system "#{bin}/gen-dto", "--version"
    install: |
      bin.install "gen-dto"
